name: cfde
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.0.5
    - r-irkernel=1.1
    - sourmash
    - snakemake-minimal
    - ipykernel
    - r-dplyr 
    - r-metacoder 
    - r-readr
